import warnings
import os
import json 
from pydantic import BaseModel, Field
from typing import Optional
from epidemiqs.utils.utils import find_files_repo
from dataclasses import dataclass
from dotenv import load_dotenv
from typing import List
from termcolor import colored
from pydantic_ai import Agent, RunContext, ModelRetry, Tool
from os.path import join as ospj
from epidemiqs.agents.tools import LiteratureReview
import traceback
from epidemiqs.utils.latex_compiler import compile_tex,generate_appendix_latex
from datetime import date
from epidemiqs.utils.llm_models import choose_model
from epidemiqs.utils.utils import log_tokens
from epidemiqs.utils.config import get_settings
cfg=get_settings()
warnings.simplefilter("ignore")

llm_model=choose_model()["experts"]
llm_model="gpt-4.1-mini-2025-04-14" # choose_model()["experts"]


output_dir = os.path.join(os.getcwd(), "output")

tokens=0
@dataclass
class PaperSection(BaseModel):
    """A dataclass to hold paper section information."""
    section_name: str= Field(None, description="Name of the section, e.g., title, abstract, introduction, background, methods, results, discussion, conclusion, appendix") 
    section_content: str = Field(None, description="Content of the section in LaTeX code in raw string format")
    references:str= Field(None, description="References for the section, in bibitem format")

system_prompt_reporter=r"""You are a skilled scientific writer tasked with writing articles in LaTeX format with nature level standard. \
                    Write in a scientific, neutral tone consistent with IEEE Transactions. Clearly explain each finding, design, and outcome related to each agent. Do not cite agents for their output."
                    Use appropriate LaTeX markup (e.g., , \textbf{}, etc.) to structure the content. \
                    Each time use will tell to to focus on only one section, Just wrtie the text for the specific section in full detail using the information you have, 
                    use output of  relavent agents, such as tables(for Discussion), figure(insert in Results section)  (always use  figures file names, e.g. figure_x.png, use only its name with .png),etc to make the report more complete.
                    make sure to mention and completely explain  the reasoning of agents in paper as it is important to have strong  logic for the decisions.
                    you can read the  JSON file using the tool read_json_file (to read log, literature review, etc that are saved in JSON format)
                    see which agent info is useful for that step of writing e.g, the ScenarioManager can be great for gathering information about the topic, 
                    so it is good to look through its input and output. \n
                    each of this section should be more than 3000  characters. \n
                    Make sure include  figures ( in  png format), tables, models and reasoning generated by agents in the section if relevant\n
                    
                    Some general suggestion are as below so you can consider according to user prompt in writing requested section:
                    Warning: avoid using Underscores _ in the text, Labels, References, use hyphens - instead. Underssores are only allowed in includegraphics for loading figures.
                    They should be in literature review JSON file, if not, no references should be used.
                    Important Never use underscore "_" in label  of figures and tables and references.
                    you generate the output as following:
                    -section_name: the name of the section, e.g. title, abstract, introduction, background, methods, results, discussion, conclusion, appendix
                    -section_content: the content of the section in LaTeX code in raw string format.\n
                    for example:
                    \begin{section}{Introduction}
                     your content here ....\n
                    -references: the references for the section, in bibitem format for Latex e.g. \bibitem{ref1} Author, Title, Journal, Year.
                    ___________________________\n
                    Important: Bibliography MUST Necessarily be in bibitem format, Never make up or create the references by yourself( avoid hallucination).  ALL refeences MUST come from literature review file proved!!

                    Important:the section_content MUST always be latex code in raw string\
                    **Important**: do not include full bibliography entries inline in the body text of the section_content of the section,  you must Separately  collect and store cited reference data in references field.
                    Important: Use \cite{} command to reference the papers in the section_content, and bring the full bibliography entries in the references field. Make sure that the key in \cite{} command matches exactly the \bibitem key in the references section. Ensure each key is unique and avoid using hyphens or underscores in bibitem keys.
                    **:Important**: Your report Must be based on the information provided by the user, and you should not invent or hallucinate any information. if no infromation, just mention that there is no information available.
                    **:Important**: Ensure the citation key in the text matches exactly the \bibitem key exactly.
                    **:Very Important**:: **Maximum allowed data columns = four**.  
                    If the data you must show needs **more than four data columns**, you **MUST** split the table into **two (or more) side-by-side sub-tables** .
                    """
r"""
                You are a proficient scientific writer tasked with composing articles in LaTeX format adhering to Nature-level standards. \
                 You utilize the save_to_latex tool, ensuring the content is LaTeX code in raw string format. \
                Employ appropriate LaTeX markup (e.g., \textbf{}, \textit{}, etc.) to structure the content effectively. \
                Each time, the user will specify a single section to focus on. Write the text for that section in comprehensive detail using the available information. \
                Incorporate outputs from relevant agents, such as tables, figures, etc., to enhance the report's completeness. \
                Ensure the reasoning of agents is thoroughly explained within the paper, as robust logic supporting decisions is critical. \
                You can access JSON files using the read_json_file tool (e.g., to review logs, literature reviews, or other JSON-stored data). \
                Identify which agent’s information is relevant for the writing step; for instance, the ScenarioManager is useful for gathering topic-related information, so review its inputs and outputs. \n
                Each section must exceed 3000 characters in length. \n
                Include relevant figures (in .pdf or .png format), tables, models, and agent-generated reasoning within the section when applicable. \n
                **Important**: ALWAYS write the requested section using the save_to_latex tool, and never include bibliography entries in the body text of the section. Save bibliography entries using the save_the_bibliography tool. \n
                Consider the following general guidelines based on the user’s prompt when writing the requested section: \
                Write the section using the save_to_latex tool, specifying the section name and LaTeX code in raw string format. \
                Important: Bibliography entries MUST be in bibitem format and saved using the save_the_bibliography tool. Never fabricate or invent references (avoid hallucination). \
                References must come from the literature review JSON file; if none are available, do not use references.
                """
latex_writer=Agent(llm_model,
                system_prompt=(r"""you are a professional LaTeX code writer and debugger and you return only LaTeX code in raw string, 
                recieve the input from the user and debug the text of errors. Some of the common errors are as below: 
                    1-All mathematical notations are written in proper LaTeX math mode (e.g., using $...$, \(...\), or \begin{equation}...\end{equation}).,
                    2-All symbols and operators (such as subscripts, superscripts, Greek letters, and math functions) are correctly formatted using LaTeX conventions
                    3-All special characters (e.g., _, &, #, %, \) are appropriately escaped in text mode (do not change them in math mode or begin{figure} mode).
                    4- remove any \input{filename} or \include{filename} commands, except for figures.
                    5-all figures  paths MUST be only the name of figure. (e.g. \begin{figure}[h]
]                                    \includegraphics[width=1\textwidth]{results_02.png}  
                                        ......
                                            \end{figure}\n """   
r"""                6 (important) Never use underscore _ in Labels of figures and tables, reference ->replace them hyphens - and modify text accordingly(Exception:Never Ever Change underscore _ the figure path in includegraphics, since it is path to load the file and must be exact.\n)
                    6.1- in  math equations, ensure unverscores _  are correcctly formattted using \_ AND $ or \[ \] or \begin{equation}...\end{equation}.\n
                    7- Never begin{document} or \end{document} in the text, if there is any, remove them.

                These were just examples, Make sure to debug it of any errors that may not be listed here, use your own knowledge to debug the latex code,
                ->Imoportant: keep the content the same (NEVER add or remove content, JUST debug the given text)
                Always Just return the core LaTeX code requested, witout another explanation.
                
                """)
                )
@dataclass
class FigureTracker(BaseModel):
    """A dataclass to hold figure information."""
    figures_list:List[str] = Field(None, description="List of figures")

figure_tracker_agent=Agent(model=llm_model,
                            system_prompt=r"""your job is detect  all the figure from the latex code and put it in the output. (use the exact latex code for figure, do not change it)
                            e.g. result=[
                            \begin{figure}[h]
                            \centering
                            \includegraphics[width=1\textwidth]{results_02.png}
                            \caption{Results of the experiment}
                            \label{fig:results}
                            \end{figure},\begin{figure}[h]
                            \centering
                            \includegraphics[width=1\textwidth]{results_03.png}
                            \caption{Results of the experiment}
                            \label{fig:results}
                            \end{figure}
                            ], if there are no figures, return None. you must return all the figures in the latex code as it is.
                            """,
                            output_type=FigureTracker,
                            #model_settings={
                            #    "temperature": 0.0,
                            #},
                            end_strategy="exhaustive",
                            retries=10,
                            )
async def clean_latex(latex_content:str,latex_agent=latex_writer,prompt:str="")->str:
    global tokens
    debugged_latex=await latex_writer.run(r"The Below is the latex code and  of  full latex error , reflect on text and return a cleaned latex code that is free of any error and it is formatted correctly(specially make sure all special characters are inserted properly using $$ or \( \)),\n"+prompt+"\n"+latex_content)
    tokens += debugged_latex.usage().total_tokens
    cleaned_content= debugged_latex.output.replace("```latex", "").replace("```", "").strip()
    print(colored("LaTeX  is cleaned. ","blue"))
    return cleaned_content


reporter_agent = Agent(
                    model=llm_model
                    ,system_prompt=system_prompt_reporter
                    ,retries=10
                    ,output_type=PaperSection
                    ,end_strategy="exhaustive")         


reviewer_agent_system_prompt=r"""You are a sharp, precise and excellent reviewer agent who respond by Chain-of-Thought. your job is to review the paper and provide comments on section of how to imporove them.
        I want you to provide section-wise comments on the paper, that solely focus on how to improve that section, I want you to make sure that content is accurate, well-structured, well-reasoned, and free of errors. Also make sure that are not unnecessary or redundant information in the text.
        Make sure that each figure  is only inserted once in the text (same paths for includefigures means redundance), and if there are redundancy, provide comment to remove repetitive figures.
        Finally score  the paper from 0 to 100, where 0 is the worst(not suitable for publishing) and 100 is groundbreaking(Suitable to be published at Nature, Grounbreaking work)(50 is margin of acceptance). each section weight is as 10 for writing quality, 15 for clarity, 20 for accuracy, 20 for novelty, 15 for structure, 10 for reasoning, 10 for references, 10 for reproducibility.
        """
@dataclass
class ReviewSections(BaseModel):
    """A dataclass to hold  comments sections of the report."""
    comments_on_title: str = None
    comments_on_abstract: str = None
    comments_on_introduction: str = None
    comments_on_methods: str = None
    comments_on_results: str = None
    comments_on_discussion: str = None
    comments_on_conclusion: str = None
    total_score: Optional[int] = Field(None, description="Total score")

###############

r"""
#@reporter_agent.tool_plain
async def save_the_bibliography(references:str):

        Args:
            content (str): The latex code of references to save.

        Returns:
            str: A message indicating where the file was saved.
        global tokens
        print(colored(f"Saving bibliography...\n","blue"))
        print(colored(references,"blue"))
        cleaned_content=await clean_latex(f"{references}\n"+r" Please also make sure all the references must be bibitem format. it should  just contain the references themselves, remove possible section header, remove all \beign or \end commands. \n")
        paper_report.append_references(cleaned_content)
        return f"LaTeX  content for references section succesfully saved."
 
"""

def extract_data(data, max_length=400_000):
    """ Extract data from JSON-like structures and format it as a string with maximum length,  (120K character~30K tokens.)"""
    def _extract(data, current_length, result):
        if current_length >= max_length:
            return current_length, result[:max_length]
        
        if isinstance(data, dict):
            for key, value in data.items():
                #print(colored(current_length, "cyan"))
                if current_length >= max_length:
                    return current_length, result[:max_length]
                line = f"{key}: {_extract(value, 0, [])[1]}"
                line_length = len(line)
                if current_length + line_length > max_length:
                    return current_length, result[:max_length]
                result.append(line)
                current_length += line_length + 1  
            return current_length, "\n".join(result)
        
        elif isinstance(data, list):
            for item in data:
                #print(colored(current_length, "cyan"))
                if current_length >= max_length:
                    return current_length, result[:max_length]
                item_length, item_result = _extract(item, 0, [])
                if isinstance(item_result, list):
                    item_result = "\n".join(item_result)
                item_length = len(item_result)
                if current_length + item_length > max_length:
                    return current_length, result[:max_length]
                result.append(item_result)
                current_length += item_length + 1 
            return current_length, "\n".join(result)
        
        else:
            str_data = str(data)
            #print(colored(current_length, "cyan"))
            if current_length + len(str_data) > max_length:
                return current_length, result[:max_length]
            return current_length + len(str_data), [str_data]
    
    total_length, result = _extract(data, 0, [])
    if isinstance(result, list):
        result = "\n".join(result)
    return result[:max_length]



class ReportWriting():
    def __init__(self, _llm_model=choose_model()["experts"], scientist_llm=cfg.llm.scientists.model,report_writer_llm=cfg.llm.experts.model):
        pass
class PaperReport:
    def __init__(self, title="", author=f"EpidemIQs, Primary Agent Backone LLM: {cfg.llm.scientists.model},  LaTeX Agent LLM : {cfg.llm.experts.model}"):
        """Initialize the PaperReport with empty sections and references"""
        print(colored(f" EpidemIQs, Backone LLM: {cfg.llm.scientists.model}, Written Using: {cfg.llm.experts.model}", "green"))
        self.author = author
        self.sections = {
            "title": title,
            "abstract": "",
            "introduction": "",
            "background": "",
            "methods": "",
            "results": "",
            "discussion": "",
            "conclusion": "",
            "appendix": ""
        }
        self.references = ""
        self.latex_content=None
        #self.reporter_agent=
        self.reviewer_agent=Agent( 
            model=llm_model,
            system_prompt=reviewer_agent_system_prompt,
            output_type=ReviewSections,
            #model_settings={
            #    "temperature": 0.0,
#
            #},
            )
        self.review_results=None
        print(colored(f"Reporter Agent Using model: {reporter_agent.model.model_name}", "green"))
    def append_section(self, section_name: str, content: str):
        """Append content to a specific section"""
        if section_name.lower() in self.sections:
            self.sections[section_name.lower()] = content
        else:
            raise ValueError(f"Invalid section name: {section_name}")

    def append_references(self, references: str):
        """Append bibliography content"""
        self.references += references

    async def generate_latex(self) -> str:
        """Generate complete LaTeX content from all sections"""
        global tokens
        if self.sections["background"]=="" or self.sections["background"]==None:
            self.background=await self.write_background()

        cleaned_references=await clean_latex(f"{self.references}\n"+r"""**Without Changing the content of above references, do the following:**\n -Please make sure it free of any LaTeX error and\n : 2-all the references must be bibitem format. \n2-it must contain the  list of references using only, remove \begin{thebibliography} or \end{thebibliography}—just the raw \bibitem entries.\n)#3- Ensure  all references are authetic and not redundant.\n""")
        #cleaned_references= await clean_latex(f"{self.references}\n"+r""" Please ensure all referenecs are authentic, remove any reference that is not in the following \n"""+"")
        
        self.references=cleaned_references
        self.latex_content = (
            "\\documentclass{article}\n"
            "\\usepackage[utf8]{inputenc}\n"
            "\\usepackage{amsmath}\n"
            "\\usepackage{algorithm}\n"
            "\\usepackage{algpseudocode}\n"
            "\\usepackage{graphicx}\n"
            "\\usepackage{hyperref}\n"
            "\\usepackage{natbib} \n"
            "\\usepackage{geometry}\n"
            "\\usepackage{booktabs}\n"
            #"\\usepackage{cite}\n"
           "\\graphicspath{./}\n"
            "\\usepackage{tikz}\n"
            "\\usepackage{lipsum} % For dummy text\n"
            "\\usepackage{eso-pic} % For placing content on every page\n"
            "\\newcommand\\BackgroundConfidential{%\n"
            "    \\put(0,0){%\n"
            "        \\parbox[b][\\paperheight]{\\paperwidth}{%\n"
            "            \\vfill\n"
            "            \\centering\n"
            "            \\tikz[remember picture,overlay] \\node[scale=5,opacity=0.2,rotate=45,align=center] {Warning:\\\\Generated By AI\\\\ \\textbf{EpidemIQs}};\n"
            "            \\vfill\n"
            "        }%\n"
            "    }%\n"
            "}\n"
            f"{self.sections['title']}\n"
            f"\\author{{{self.author}}}\n"
            #"\\date{\\today}\n"
            "\\date{November 2025}\n"
            "\\begin{document}\n"
            "\\AddToShipoutPictureBG{\\BackgroundConfidential}\n"
            "\\maketitle\n\n"
            f"{self.sections['abstract']}\n\n"
            f"{self.sections['introduction']}\n\n"
            f"{self.sections['background']}\n\n"
            f"{self.sections['methods']}\n\n"
            f"{self.sections['results']}\n\n"
            f"{self.sections['discussion']}\n\n"
            f"{self.sections['conclusion']}\n\n"
            "\\begin{thebibliography}{99}\n\n"
            f"{self.references}\n"
            "\\end{thebibliography}\n"
            "\\newpage\n"
        )
        #if not self.review_results:
            #if self.review_results.total_score<95:
        review_results=await self.reviewer_agent.run(user_prompt=(
            f"Please review the paper and provide comments on each section, and give a score from 0 to 100. \n\n"
            f"Title: {self.sections['title']}\n\n"
            f"Abstract: {self.sections['abstract']}\n\n"
            f"Introduction: {self.sections['introduction']}\n\n"
            f"Background: {self.sections['background']}\n\n"
            f"Methods: {self.sections['methods']}\n\n"
            f"Results: {self.sections['results']}\n\n"
            f"Discussion: {self.sections['discussion']}\n\n"
            f"Conclusion: {self.sections['conclusion']}\n\n"
        ))
        tokens+=review_results.usage().total_tokens
        self.review_results=review_results.output
        print(colored(f"Review results: {self.review_results}", "yellow"))
        self.latex_review_results=await clean_latex(f"{self.review_results}\n",prompt=r""" Please rewrite the above text in LaTeX code wihtout changing its content. Remmeber the latex file is already initialized, Just provide the core LaTeX code that goes inside the document body. (i.e. exclude \documentclass, \begin{document}, and \end{document}), etc.\n\n""")
        self.latex_content += ( 
                            "\\section*{Supplementary Material}\n"
                            f"{self.sections['appendix']}\n\n"
                            #f"\\newpage\n\n"
                            #"\\section*{Feedback on Sections}\n"
                            #f"{self.latex_review_results}\n\n"
                            #"\\end{document}"
                            )
        try:
            self.latex_content += ( generate_appendix_latex( images_dir=ospj(os.getcwd(),"output") )
                                   +"\\end{document}"
                                   )   
        except Exception as e:
            print(colored(f"Error generating appendix LaTeX: {e}", "red"))
            self.latex_content += "\\end{document}"

    async def  literature_review(self, query:str)->str:
        global tokens
        literature_instance=LiteratureReview(json_file=ospj("output","back_grounds.json"),sort_type="recency")
        back_ground_results=await literature_instance.conduct_review(query=query)
        back_ground_cut=extract_data(back_ground_results, max_length=400_000)
        return back_ground_cut
    
    async def write_background(self) -> str:
        """Get the LaTeX content as a string"""
        global tokens
        self.background_agent=Agent(model=llm_model,
            system_prompt=(r"""you are professional scientific writer, and you write the concise background section of the paper based on the literature review provided by the user. This is a critical section of the paper, and you must ensure that it is well-written, scientifically accurate, and free of errors. \
                            you receive a paper and you have to design a query or multiple queries to send to Semantic Scholar API to find related works, and write a Background section, according to literature recieved to complete the paper, to see how novel is this work, do not exaggerate the novelty of this work, write background and judge its novelty based on the literature.
                            Use a proper query to make sure that we get the most recent and relevant papers, if the query does not return any paper, try other query to get the papers.
                            Write  a detailed background  section by in section_content tool with name of the section_name as *Background* and  content in latex code in raw string and use \cite{...} to reference,
                            For referencing use \cite{} command to reference and give credits to them by mentioning their work and contributiomn, for example:" in \cite{Xu2010} Xu et al. proposed method X, etc" , BUT remember NEVER include full bibliography entries inline in the body text of the content of the section, you MUST Separately, collect and store cited reference data in references field.
                            Important: Bibliography MUST Necessarily be in bibitem format, And never make up or create the references by yourself(hallucination). The References MUST come from literature review file provided!! ( Never make them up by your own knowledge)\n
                            you generate the output as following:
                        -section_name: the name of the section, e.g. Background\n
                        -section_content: the content of the section in LaTeX code in raw string format.\n
                        for example:
                        \section{Background}
                        your content here ....\n
                        -references: the references for the section, in bibitem format for Latex e.g. \bibitem{ref1} Author, Title, Journal, Year.
                        ___________________________\n
                        Important: Bibliography MUST Necessarily be in bibitem format, Never make up or create the references by yourself( AVOID hallucination).  ALL refeences MUST come from literature review you performed!!"""),
                    
                    tools=[

                        Tool(self.literature_review, takes_ctx=False),
                        ],
                        model_settings={
                            #"temperature": 0.0,
                            "parallel_tool_calls": False,
                            },                         
                        end_strategy="exhaustive",
                        output_type=PaperSection,
                        retries=20,
                        )
        prompt=(f"""Here is the paper sections:\n {"-"*25}\n{self.sections}\n{"-"*25}\n Please conduct a literature search and  write a background section for the paper\n\n"""
                +r"""**Important**: ALWAYS use  \cite{"bibitem key"} command to reference ,do not include full bibliography entries inline in the body text of the content of the section, Separately, collect and store cited reference data in references.
                Make sure that the key in \cite{} command matches exactly the \bibitem key in the references section.
                Ensure each key is unique and avoid using hyphens or underscores in bibitem keys.
                Make sure that that background well addressed similar works and their limitations, and the novelty of this work is well explained, scientifically accurate and without exaggeration and repeatting redundant information."""
                +f"Please do not repeat what has alredy mentioned in introcution section as follow:\n{self.sections['introduction']}\n\n")
        background=await self.background_agent.run(user_prompt=prompt)
        await self.save_as_latex("background", background.output.section_content)
        await self.save_the_bibliography(background.output.references)
        tokens += background.usage().total_tokens
        #print(colored(f"Background section: {background}", "yellow"))
        print(colored(f"\nBackground  saved succesfully section : {self.sections["background"]}\n", "yellow"))
        
    def save_final_latex_file(self, output_dir=os.path.join(os.getcwd(), "output") ,file_name:str="report.tex") -> str:
        
        try:
            os.makedirs(output_dir, exist_ok=True)
            file_path = os.path.join(output_dir, file_name)
            with open(file_path, 'w', encoding="utf-8") as f:
                f.write(self.latex_content)
                print(colored(f"Scientific report LaTeX file saved as {file_path}", "green"))
            compile_tex(file_path)
            if os.path.exists(file_path.replace(".tex", ".pdf")):
                print(colored(f"PDF file generated successfully.", "green"))
        except Exception as e:
            return f"Error creating directory: {e}"
        
    async def save_as_latex(self,section:str,latex_content:str):
        """save the content for the section LaTeX code.

        Args:
            section (str): The section name to save,only one word name is allowed.[title, abstract, introduction,background, methods, results, discussion, conclusion, appendix]
            content (raw string): the content for section  in LaTeX code in raw string.

        Returns:
            str: A message indicating where the file was saved.
        """
        global tokens
        if section.lower() not in self.sections:
            return f"Error: Invalid section name '{section}'. Valid section names are: {', '.join(self.sections.keys())}"
        print(colored(f"Saving LaTeX file...\n","blue"))
        if latex_content=="" or latex_content==None:
            return f"Error: LaTeX content for {section} section is empty. please provide valid content."
        print(colored(f"section: {section}","blue"))
        print(colored(f"content: {latex_content}","blue"))
        cleaned_content=await clean_latex(latex_content,prompt=r"please also remove the anything other than the figure name in the \includegraphics in the figure environment, no directory path should be included! \n")
        self.append_section(section, cleaned_content)
        return f"LaTeX  content for {section} section succesfully saved."

    #@reporter_agent.tool_plain
    async def save_the_bibliography(self,references:str):
            """Saving teh references in the in the reference section of the LaTeX file. The format should be bibitem.

            Args:
                content (str): The latex code of references to save.

            Returns:
                str: A message indicating where the file was saved.
            """
            global tokens
            print(colored(f"Saving bibliography...\n","blue"))
            print(colored(references,"blue"))
            cleaned_content=await clean_latex(f"{references}\n"+r""" Please also make sure all the references must be bibitem format. it should  just contain the references themselves, remove possible section header, remove all \beign or \end commands. \n""")
            print(colored(f"cleaned content: {cleaned_content}","red"))
            self.append_references(cleaned_content)
            return f"LaTeX  content for references section succesfully saved."
    

#paper_report = PaperReport()
    


def get_python_codes(directory:str):
    """get python scripts saved the repo directory and extract the code from them."""
    directory = os.path.join(os.getcwd(), "output")  if directory is None else directory
    files = find_files_repo(directory, ".py",full_path_bool=True)
    code=""
    for file in files:
        #print(file)
        with open(file, 'r') as f:
            file_content = f.read()
            code+=extract_data(file_content)
    return code



@reporter_agent.tool_plain
def read_json_file(path: str):
    """
    This function reads a JSON file and extracts its data as string.
    
    Args:   
        path: the path to the log JSON file
    """
    print(colored(f"Reading the JSON file at {path}", "blue"))
    try:
        with open(path, 'r') as file:
            data = json.load(file)
        return extract_data(data)
    except FileNotFoundError:
        return f"Error: File not found at {path}, if the file path is correct,Then the file is not generated."
    except Exception as e:
        error_traceback = traceback.format_exc()
        return f"Error reading JSON file: {error_traceback}"


async def generate_report_sections(llm_model_for_writer=reporter_agent.model, reporter_agent=reporter_agent,log_name="log.json", lit_review_name="literature_review.json",paper_report=None,report_name="report.tex",paper_class=PaperReport):
    import time
    """Generate sections of the report using the reporter agent
    Args:
        llm_model_for_writer (str): The model name for the writer agent.
        reporter_agent (Agent): The reporter agent instance.
        log_name (str): The name of the log file.
        lit_review_name (str): The name of the literature review file.
    """
    paper_report= PaperReport()

    global tokens
    sections = [
        "title",
        "abstract",
        "introduction",
        "methods",
        "results",
        "discussion",
        "conclusion",
        "appendix"
    ]
    directory = os.path.join(os.getcwd(), "output")
    log_path = ospj(directory, log_name)
    lit_review_path = ospj(directory, lit_review_name)
    start_time = time.time()
    st=start_time
    for _ in range(1):
        if not paper_report.review_results:
            for section in sections:
                print(colored(f"Processing section: {section}", "cyan"))


                if section.lower() == "appendix":
                    # Appendix has a completely different prompt structure focusing on pseudocode
                    python_code_content = get_python_codes(directory=directory)
                    my_prompt = (
                        
                        f"Please write the section {section}, and Just provide the core LaTeX code that goes inside the document body for {section} \n"
                        r"""For this section,Appendix, please write concise, high-level and single algorithmic style pseudocode in LaTeX that captures all the key steps from the provided code. """
                        r"""The pseudocode should cover multiple code sections, maintaining clarity and structure while avoiding verbosity having code-like structure other than being verbal. """
                        r"""Ensure the order of actions reclsflects the logical flow of the process (the current order may not be correct). """
                        r"""Focus on algorithmic code-like and professional representation, and avoid verbal descriptions as much as possible."""
                        r"""Remember: Only pseudo code is enough for this section, avoid writing any other content, feel free to break it into multiple algorithms if needed. """
                        "Important: Ensure it is compatible with algpseudocode and algorithm packages in LaTeX.  """
                        f"{python_code_content}\n\n"
                        # Note: The original had "Do not " at the end, which seemed incomplete. Removed it. If it was intentional, add it back.
                    )
                    #print(colored(f"Prompt for {section}:\n{my_prompt}", "red"))
                else:     
                    # --- Determine Data Source Path ---
                    # Introduction uses both lit review and log, others use only log (or lit review for references)
                    if section == "introduction":
                        data_path_desc = f"JSON files: {lit_review_path} and {log_path}"
                        my_prompt = f"Write ONLY the {section} section by reading the data stored at {data_path_desc}.\n"
                        my_prompt += f"Write Just and Only the requested {section}, and not any other section.\n"
                        my_prompt +=r"Ensure to use the literature review file for references and reference to most of the relevant works using \cite{}  so it builds strong foundation for the work by mentioning previous works.\n"
                        my_prompt +=( r"""**Important**: ALWAYS use  \cite{"bibitem key"} command to reference ,do not include full bibliography entries inline in the body text of the content of the section, Separately, collect and store cited reference data in references.
                                     Make sure that the key in \cite{} command matches exactly the \bibitem key in the references section.\n
                                     Ensure each key is unique and avoid using hyphens or underscores in bibitem keys.""")
                        
                    else:
                        data_path_desc = f"JSON file: {log_path}"

                        # ---Base Prompt for Other Sections ---
                        my_prompt = f"Write ONLY the {section} section by reading the data stored at {data_path_desc}.\n"
                        my_prompt += f"Write Just and Only the requested {section}, and not any other section.\n"
                        # While other sections primarily use the log, they might need the lit review for references.
                        # The prompt later specifies where to get references from.
                        if section.lower() not in ["title", "abstract","results"]:
                            data_path_desc += f" (and potentially {lit_review_path} for references)"


                    # --- Formatting Examples ---
                    if section == "title":
                        my_prompt += r"For example: \title{title for this paper}" + "\n"
                    elif section == "abstract":
                        my_prompt += r"For example: \begin{abstract} this is the abstract \end{abstract}" + "\n"
                        
                    elif section.lower() not in ["title", "abstract"]: # General section format
                        my_prompt += fr"For example: \section{{{section.capitalize()}}} \n [Text for the section]..." + "\n" # Capitalize for convention

                    # --- Instructions for Sections with Body Content (Not Title/Abstract) ---
                    if section.lower() not in ["title", "abstract"]:

                        # --- Data Source Details ---
                        log_path_desc_detail = (
                            r"""Details on the Log JSON file structure: """
                            r"""All agent inputs and outputs can be found there. Make sure to look at all agent outputs """
                            r"""and include relevant information, especially reasoning info. The data is structured as: """
                            r""""Phase Name": { "iteration_{iteration_number}": [ "data": phase data, """
                            r"""} ] }"""
                        )
                        lit_path_desc_detail = (
                            r"""Details on the Literature Review JSON file structure: """
                            r"""{ "results": [ { "query": "query 1", "papers": [ """
                            r"""{ "paper_title": "topic 1", "abstract": "abstract 1", "citation": "Citation 1", """
                            r""""summary (tldr)": { "model": "tldr@v2.0.0", "text": "a summary 1" }|None }, ...] }, ...] }"""
                        )

                        if section == "introduction":
                            my_prompt += lit_path_desc_detail + "\n" + log_path_desc_detail + "\n"
                        else:
                            my_prompt += log_path_desc_detail + "\n" # Lit review details added implicitly with reference instructions


                        if section.lower()  in ["introduction", "methods"] :
                            my_prompt += (                      
                                f"Extract references ONLY from the literature review file ({lit_review_path}).\n"
                                f"In text, cite references using \\cite{{CITATION_KEY}}.\n"
                                f"bibliography  for references actually cited in {section}, must be in bibitem format.\n") 
                        my_prompt+=(f"NEVER cite works NOT present in the literature review file, to avoid halluciantion.\n"
                            )
                        if section.lower() == "methods":
                            my_prompt += (
                                f"For the {section} section, thoroughly explain the mathematical foundations and reasoning behind the experimental design. Present all calculations, algorithms, and analytical approaches with clear justification to demonstrate the methodological rigor of this work.\n"
                                +"Make sure tables are fitted to text width, use concise column names or abbreviations, and ensure they are well-formatted.\n"
                                )
                        # --- Content Quality and Inclusion (Not for Introduction, Title, Abstract) ---
                        if section.lower() in ["results", "discussion"]:
                            if section.lower() == "discussion":
                                figures=await figure_tracker_agent.run(f"Please extract all the figures from the latex code and return them as a list of strings, if there are no figures, return None.\n"+ paper_report.sections["results"])  
                                fig_list=figures.output.figures_list
                            elif section.lower() == "results":
                                figures=await figure_tracker_agent.run(f"Please extract all the figures from the latex code and return them as a list of strings, if there are no figures, return None.\n"+ paper_report.sections["methods"])
                                fig_list=figures.output.figures_list
                            my_prompt += (
                                "Use chain of thought reasoning to ensure the writing for this section is excellent, comprehensive, and accurate based on the provided data.\n"
                                "Include  relevant figures,  and write tables, models, and analyses generated by the agents (found in the log file) that are suitable for this section.\n"
                                "Remember, generated figures and tables are valuable and should be included and explained well within the section.\n"
                            )
                            if section.lower() == "results":
                                plot_paths = find_files_repo(repo_path=ospj(os.getcwd(), 'output'), extension=".png")
                                my_prompt += (
                                    f"Important Reminder for Results: Ensure relevant plots from simulation results are included and appropriately captioned (try to include all simualtion results if they are not the same.). Available plots are as below, include those which are related to simulation results\n"
                                    f"{'-'*25}\n{plot_paths}\n{'-'*25}\n"
                                    +(f"Below figures are already present in previous sections,**DO NOT** include them again, but refer to them if relevant\n" 
                                    f"{'-'*25}\n{fig_list}\n{'-'*25}\n" ) )
                            if section.lower() == "discussion" :
                                    my_prompt += (f"Below figures are already present in Results sections, so do not repeat them, but refer to them if relevant\n" 
                                    +f"{'-'*25}\n{fig_list}\n{'-'*25}\n")
                                    
                            my_prompt +=(f"Make sure the results section completely describes these results, referencing the plots. Make sure than only relevant figures to {section} are included  "
                                   + "Make sure tables are fitted to text width, use concise column names or abbreviations, and ensure they are well-formatted.\n"
                                    +r"""**Important**: ALWAYS  use \cite{} command to reference and bring the bibliography in references section.
                                    do not include full bibliography entries inline in the body text of the content of the section, Separately, collect and store cited references  in the references section \n"""

                            )


                        # --- Section-Specific Reminders ---
                        if section == "introduction":
                            my_prompt += "Important Reminder for Introduction: You MUST include the research question (or the problem) this research aims to answer. This question IS found in the input or description of the 'ScenarioManagerAgent' in the log file.\n"
                            my_prompt += "Do not include any figures or tables in the introduction section. Make sure do to only referene those works that are in the literature review.\n"
                        if section == "conclusion":
                            my_prompt = f"Write ONLY the {section} section by reading the data stored at {data_path_desc}.\n"
                            my_prompt += f"Write Just and Only the requested {section}, and not any other section.\n"
                            my_prompt += "Important Reminder for Conclusion: Remember that the Conclusion should summarize the main findings, discuss limitations of the research, and suggest possible future directions. Please address these aspects completely.\n"
                            my_prompt += f"the previous sections are:\n{paper_report.sections}\n\n "
                            my_prompt += "-"*25 + "\n"
                            my_prompt += r"Now Write a brief, impactful \section{conclusion} that summarizes the key points, reinforces the main message, and leaves a lasting impression. Ensure it is clear, engaging, and aligns with the tone and purpose of the content. \n"
                        if section.lower() not in ["title", "abstract"]:
                            my_prompt += ("Hint: use \\section{} command to write the section title in LaTex\n")
                    my_prompt += (r"if using underscrips in the text, please use \_ and avoid using it in label of figures or tables. it is fatal\n")
                                 

                #print(colored(f"Prompt for {section}:\n{my_prompt}", "red"))
                print("-" * 80) # Separator
                result = await reporter_agent.run(my_prompt)
                #print(colored(f"raw results for {section}:\n{result}", "magenta"))

                print(colored(f"Response for {result.output.section_name}: {result.output.section_content}", "magenta"))
                while result.output.section_name.lower()!=section or result.output.section_content==None:
                    print(colored(f"Error: Invalid section name or empty content occured! we send the request to API again!", "red"))
                    result = await reporter_agent.run(my_prompt)
                await paper_report.save_as_latex(section=result.output.section_name, latex_content=result.output.section_content)
                await paper_report.save_the_bibliography(references=result.output.references) if result.output.references else None
                tokens += result.usage().total_tokens
                

                #content=paper_report.latex_content.get(section, {})
                #prompt = f"""\n\n{section}:\n{content}"""
                #print(colored(f"Response: {result.output}", "magenta"))
            
            await paper_report.generate_latex()
            paper_report.save_final_latex_file(file_name="initial_"+report_name)    

        elif paper_report.review_results:
            for section in sections:
            #for section in ['results']:
                prompt=f"""The written section {section} of the paper is as below:\n\n{paper_report.sections[section]}\n\n"""
                prompt += f"""\n The reviewer agent has provided the following comments on the section:\n\n{paper_report.review_results}\n\n"""
                prompt += f"""\n I want to reflect on the comments through Chain-of-Thought and address them in the section {section} of the paper, and rewrite the section while being loyal and careful about the original content as it is the result of scientific work. """
                prompt += f"""\n Important:
                                        1-Soley focus on the requested section \n{section}.\n
                                        2. To make sure the writing is excellent and comprehensive, try to write as your maximum length allowed, ensuring  all information are preserved.
                                        """
                prompt += (f"Ensure all figures referenced in the text are valid and correspond to existing files listed below:\n"
                            f"Available figures: {find_files_repo(repo_path=os.path.join(os.getcwd(), 'output'), extension='.png')}\n"
                            if section.lower() not in ['title', 'abstract','introduction'] else "")
                prompt += f"""\n Important Reminder: pease ensure that suitable figures from the epxeriments are included, as they are stored as:\n{"-"*25}\n{find_files_repo(repo_path=ospj(os.getcwd(),'output'),extension=".png")}\n""" if section.lower() =="results" else ""
                prompt += f"""\n if you need review the JSON history log of workflow it is stored at:\n{"-"*25}\n{log_path}\n\n"""
                # FIX HERE
                result = await reporter_agent.run(prompt)
                print(colored(f"Response for {result.output.section_name}: {result.output.section_content}", "magenta"))
                await paper_report.save_as_latex(section=result.output.section_name, latex_content=result.output.section_content)
                await paper_report.save_the_bibliography(references=result.output.references) if result.output.references else None
                tokens += result.usage().total_tokens

            await paper_report.generate_latex()
            paper_report.save_final_latex_file(file_name="revised_"+report_name)
            total_time = time.time() - start_time
            try:
                section_time = time.time() - start_time
                file_path=ospj(os.getcwd(), 'output','tokens.txt')
                with open(file_path, 'a+') as token_file:
                    token_file.seek(0)
                    file_exists = len(token_file.read()) > 0
                    if file_exists: 
                        token_file.write(f"\nReporter Agent - {tokens} tokens, Time: {total_time:.2f} seconds")
                    else:
                        token_file.write(f"Reporter Agent -  {tokens} tokens, Time: {total_time:.2f} seconds")
            except Exception as e:
                print(colored(f"Error writing to tokens.txt: {e}", "red"))
        output_dir = os.path.join(os.getcwd(),"output")
        os.makedirs(output_dir, exist_ok=True)
        csv_file = os.path.join(output_dir, "tokens.csv")       
        log_tokens(repo=output_dir, agent_name="ReportWriting", llm_model=reporter_agent.model.model_name,
                   total_tokens=tokens, time=time.time()-st,csv_name="tokens_by_phase.csv")
        with open(csv_file, "a+") as f:
            f.write(f"{date.today()},Reporter Agent,{reporter_agent.model.model_name},{tokens}\n")
        paper_report= PaperReport()

if __name__ == "__main__": 
    async def main():
        await generate_report_sections() 
        print(f"Total tokens used: {tokens}")
        """with open("output/initial_report.tex", "r") as file:
            report_content = file.read()
            cont=extract_data(report_content, max_length=150_000)
            print(f"Loaded report content with length: {len(report_content)}")
            figures=await figure_tracker_agent.run(user_prompt=cont)
            print(colored(f"Figures: {figures}", "cyan"))"""
    import asyncio
    asyncio.run(main())
    import os
    os.system("Say Beeb Beeeeb Beeeeeb!Report generation completed successfully. Take a look!")